# Generated by Django 3.1 on 2021-06-17 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sling',
            new_name='slug',
        ),
    ]
